<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <AssemblyName>PartialMealConsumption</AssemblyName>
    <RootNamespace>PartialMealConsumption</RootNamespace>
    <LangVersion>latest</LangVersion>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>    <GameModsDir>$(RimWorldDir)\Mods</GameModsDir>
    <ModDeployDir>$(GameModsDir)\PartialMealConsumption</ModDeployDir>

    <OutputPath>$(ModDeployDir)\Assemblies\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>

    <ModRoot>$(MSBuildProjectDirectory)\..\..</ModRoot>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(RimWorldDir)\RimWorldWin64_Data\Managed\Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(RimWorldDir)\RimWorldWin64_Data\Managed\UnityEngine.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(RimWorldDir)\RimWorldWin64_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Lib.Harmony" ExcludeAssets="runtime" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\RimModUtilities\src\RimModUtilities\RimModUtilities.csproj"
                      ReferenceOutputAssembly="true"
                      Private="false"
                      Condition="'$(Configuration)' == 'Debug'" />
  </ItemGroup>

</Project>
